#!/usr/bin/bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)"
AUTH_CONFIG="${ROOT_DIR}/config/hypr/scripts/awtarchy-polkit-agent/alacritty.toml"
MAIN_CONFIG="${ROOT_DIR}/config/alacritty/alacritty.toml"
LAUNCHER="${ROOT_DIR}/config/hypr/scripts/awtarchy-polkit-agent/launcher.sh"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

[[ -f $AUTH_CONFIG ]]
[[ -f $MAIN_CONFIG ]]
[[ -f $LAUNCHER ]]

# The root-owned auth config is a safe fallback and must never import arbitrary
# user files directly. Runtime appearance parity is applied only through
# whitelisted Alacritty --option values generated by trusted launcher code.
/usr/bin/python3 - "$AUTH_CONFIG" "$MAIN_CONFIG" <<'PY'
from pathlib import Path
import sys
import tomllib

auth_path = Path(sys.argv[1])
main_path = Path(sys.argv[2])
auth = tomllib.loads(auth_path.read_text(encoding="utf-8"))
main = tomllib.loads(main_path.read_text(encoding="utf-8"))

assert main["window"]["padding"] == {"x": 22, "y": 22}
assert main["window"]["opacity"] == 0.85
assert main["font"]["size"] == 12.0

assert auth["window"]["padding"] == {"x": 22, "y": 22}
assert auth["window"]["opacity"] == 0.85
assert auth["font"]["size"] == 12.0
assert auth["scrolling"]["history"] == 0

text = auth_path.read_text(encoding="utf-8")
assert "import =" not in text
assert "~/.config" not in text
assert "/home/" not in text
PY

# Extract the exact trusted Python sanitizer embedded in launcher.sh and prove
# it follows the user's current imported Alacritty theme while refusing to copy
# executable/user-controlled configuration such as shell or key commands.
awk '
  /^# AWTARCHY_POLKIT_APPEARANCE_PY_BEGIN$/ { capture=1; next }
  /^# AWTARCHY_POLKIT_APPEARANCE_PY_END$/   { capture=0; next }
  capture { print }
' "$LAUNCHER" >"$TMP/appearance.py"
[[ -s $TMP/appearance.py ]]

HOME_FIXTURE="$TMP/home"
mkdir -p "$HOME_FIXTURE/.config/alacritty/themes/themes"
cat >"$HOME_FIXTURE/.config/alacritty/alacritty.toml" <<'EOF'
[window]
opacity = 0.73
padding = { x = 17, y = 19 }
dynamic_padding = true

[font]
size = 13.5
normal = { family = "Fixture Mono", style = "Regular" }

[terminal.shell]
program = "/tmp/never-run-me"

[[keyboard.bindings]]
key = "A"
command = "/tmp/never-run-me"

[general]
import = ["~/.config/alacritty/themes/themes/current.toml"]
EOF

cat >"$HOME_FIXTURE/.config/alacritty/themes/themes/current.toml" <<'EOF'
[colors.primary]
background = "#123456"
foreground = "#abcdef"

[colors.normal]
black = "#000001"
red = "#100001"
green = "#200001"
yellow = "#300001"
blue = "#400001"
magenta = "#654321"
cyan = "#600001"
white = "#700001"

[[keyboard.bindings]]
key = "B"
command = "/tmp/theme-command-must-not-copy"
EOF

OPTIONS="$(/usr/bin/python3 -I "$TMP/appearance.py" \
    "$HOME_FIXTURE/.config/alacritty/alacritty.toml" "$HOME_FIXTURE")"

grep -Fqx 'window.opacity=0.73' <<<"$OPTIONS"
grep -Fqx 'window.padding.x=17' <<<"$OPTIONS"
grep -Fqx 'window.padding.y=19' <<<"$OPTIONS"
grep -Fqx 'window.dynamic_padding=true' <<<"$OPTIONS"
grep -Fqx 'font.size=13.5' <<<"$OPTIONS"
grep -Fqx 'font.normal.family="Fixture Mono"' <<<"$OPTIONS"
grep -Fqx 'colors.primary.background="#123456"' <<<"$OPTIONS"
grep -Fqx 'colors.primary.foreground="#abcdef"' <<<"$OPTIONS"
grep -Fqx 'colors.normal.magenta="#654321"' <<<"$OPTIONS"

if grep -Eq 'never-run-me|theme-command-must-not-copy|terminal[.]shell|keyboard|command=' <<<"$OPTIONS"; then
    echo 'appearance sanitizer leaked executable Alacritty configuration' >&2
    exit 1
fi

grep -Fq -- '--option' "$LAUNCHER"
grep -Fq 'AWTARCHY_POLKIT_APPEARANCE_PY_BEGIN' "$LAUNCHER"

echo 'Polkit Alacritty appearance contract passed.'
