name: Test scxctl auth UI

on:
  push:
    branches: [scxctl-auth-testing]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - name: Regression
        run: bash tests/test-scxctl-auth-ui.sh
